// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCtSh2Nj-i8dHOGnQUvzZACASr4f69RfOE',
    appId: '1:719810760918:web:cd0e5e2721b72ecac63977',
    messagingSenderId: '719810760918',
    projectId: 'shop-3d4fb',
    authDomain: 'shop-3d4fb.firebaseapp.com',
    databaseURL: 'https://shop-3d4fb-default-rtdb.firebaseio.com',
    storageBucket: 'shop-3d4fb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZRJhJ6TFJNKXzdyDlOUGPEKDhetWmWQk',
    appId: '1:719810760918:android:f873ccb41509629bc63977',
    messagingSenderId: '719810760918',
    projectId: 'shop-3d4fb',
    databaseURL: 'https://shop-3d4fb-default-rtdb.firebaseio.com',
    storageBucket: 'shop-3d4fb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNt_1ctd0AY_VNoS5WHolJe7GKYxMCUdk',
    appId: '1:719810760918:ios:82c14744f32bfc6cc63977',
    messagingSenderId: '719810760918',
    projectId: 'shop-3d4fb',
    databaseURL: 'https://shop-3d4fb-default-rtdb.firebaseio.com',
    storageBucket: 'shop-3d4fb.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNt_1ctd0AY_VNoS5WHolJe7GKYxMCUdk',
    appId: '1:719810760918:ios:82c14744f32bfc6cc63977',
    messagingSenderId: '719810760918',
    projectId: 'shop-3d4fb',
    databaseURL: 'https://shop-3d4fb-default-rtdb.firebaseio.com',
    storageBucket: 'shop-3d4fb.appspot.com',
    iosBundleId: 'com.example.newsApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCtSh2Nj-i8dHOGnQUvzZACASr4f69RfOE',
    appId: '1:719810760918:web:09796cbe4a9390f6c63977',
    messagingSenderId: '719810760918',
    projectId: 'shop-3d4fb',
    authDomain: 'shop-3d4fb.firebaseapp.com',
    databaseURL: 'https://shop-3d4fb-default-rtdb.firebaseio.com',
    storageBucket: 'shop-3d4fb.appspot.com',
  );
}
